name: Update Gallery JSON

on:
  push:
    paths:
      - 'assets/gallery/**'
    branches:
      - main

permissions:
  contents: write  # ✅ allows the action to commit/push

jobs:
  generate-gallery-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gallery.json
        run: |
          GALLERY_FOLDER="assets/gallery"
          JSON_FILE="gallery.json"

          echo "[" > $JSON_FILE
          FILES=($(ls -1 "$GALLERY_FOLDER" | sort))
          for i in "${!FILES[@]}"; do
            FILE="${GALLERY_FOLDER}/${FILES[$i]}"
            if [ $i -lt $((${#FILES[@]}-1)) ]; then
              echo "  \"$FILE\"," >> $JSON_FILE
            else
              echo "  \"$FILE\"" >> $JSON_FILE
            fi
          done
          echo "]" >> $JSON_FILE

      - name: Commit and push gallery.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gallery.json
          git diff --cached --quiet || git commit -m "Update gallery.json"
          git push
