name: Sync Gallery from Google Drive

on:
  workflow_dispatch:   # Run manually
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"  # Optional: daily at 2 AM

permissions:
  contents: write  # Allows committing & pushing

jobs:
  generate-gallery-json:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Install dependencies
      - name: Install jq & wget
        run: sudo apt-get update && sudo apt-get install -y jq wget

      # Step 3: Fetch images from Google Drive
      - name: Fetch images from Google Drive
        run: |
          FOLDER_ID="18F5Vie2EWnBMY6jR0_lmCIiJu3XuoUgM"
          API_KEY="${{ secrets.GOOGLE_API_KEY }}"
          mkdir -p assets/gallery
          rm -f assets/gallery/*

          FILES=$(curl -s "https://www.googleapis.com/drive/v3/files?q='${FOLDER_ID}'+in+parents&key=${API_KEY}&fields=files(id,name,mimeType)" \
            | jq -r '.files[] | select(.mimeType | startswith("image/")) | .id + " " + .name')

          for FILE in $FILES; do
            FILE_ID=$(echo $FILE | awk '{print $1}')
            FILE_NAME=$(echo $FILE | awk '{print $2}')
            wget -q "https://drive.google.com/uc?export=view&id=$FILE_ID" -O "assets/gallery/$FILE_NAME"
          done

      # Step 4: Generate gallery.json
      - name: Generate gallery.json
        run: |
          GALLERY_FOLDER="assets/gallery"
          JSON_FILE="gallery.json"

          echo "[" > $JSON_FILE
          FILES=($(ls -1 "$GALLERY_FOLDER" | sort))
          for i in "${!FILES[@]}"; do
            FILE="${GALLERY_FOLDER}/${FILES[$i]}"
            if [ $i -lt $((${#FILES[@]}-1)) ]; then
              echo "  \"$FILE\"," >> $JSON_FILE
            else
              echo "  \"$FILE\"" >> $JSON_FILE
            fi
          done
          echo "]" >> $JSON_FILE

      # Step 5: Commit & push changes
      - name: Commit and push gallery.json & images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/gallery/* gallery.json
          git diff --cached --quiet || git commit -m "Sync gallery from Google Drive"
          git push
